In [100]:
import pandas as pd

In [101]:
data = pd.read_csv(r"netflix_titles.csv")

In [102]:
data.head()

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,NaN,United States,"September 25, 2021",2020,PG-13,90 min,Documentaries,"As her father nears the end of his life, filmm..."
1,s2,TV Show,Blood & Water,NaN,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries","After crossing paths at a party, a Cape Town t..."
2,s3,TV Show,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",NaN,"September 24, 2021",2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act...",To protect his family from a powerful drug lor...
3,s4,TV Show,Jailbirds New Orleans,NaN,NaN,NaN,"September 24, 2021",2021,TV-MA,1 Season,"Docuseries, Reality TV","Feuds, flirtations and toilet talk go down amo..."
4,s5,TV Show,Kota Factory,NaN,"Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...",India,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, Romantic TV Shows, TV ...",In a city of coaching centers known to train I...

# DATA PREPROCESSING

In [103]:
data['tags'] = data['director'] + ' ' + data['cast'] + ' ' + data['listed_in'] + ' ' + data['description']

In [104]:
data.head()

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description,tags
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,NaN,United States,"September 25, 2021",2020,PG-13,90 min,Documentaries,"As her father nears the end of his life, filmm...",NaN
1,s2,TV Show,Blood & Water,NaN,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries","After crossing paths at a party, a Cape Town t...",NaN
2,s3,TV Show,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",NaN,"September 24, 2021",2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act...",To protect his family from a powerful drug lor...,"Julien Leclercq Sami Bouajila, Tracy Gotoas, S..."
3,s4,TV Show,Jailbirds New Orleans,NaN,NaN,NaN,"September 24, 2021",2021,TV-MA,1 Season,"Docuseries, Reality TV","Feuds, flirtations and toilet talk go down amo...",NaN
4,s5,TV Show,Kota Factory,NaN,"Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...",India,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, Romantic TV Shows, TV ...",In a city of coaching centers known to train I...,NaN

In [105]:
data = data[['show_id', 'type', 'title', 'tags']]

In [106]:
data

,show_id,type,title,tags
0,s1,Movie,Dick Johnson Is Dead,NaN
1,s2,TV Show,Blood & Water,NaN
2,s3,TV Show,Ganglands,"Julien Leclercq Sami Bouajila, Tracy Gotoas, S..."
3,s4,TV Show,Jailbirds New Orleans,NaN
4,s5,TV Show,Kota Factory,NaN
...,...,...,...,...
8802,s8803,Movie,Zodiac,"David Fincher Mark Ruffalo, Jake Gyllenhaal, R..."
8803,s8804,TV Show,Zombie Dumb,NaN
8804,s8805,Movie,Zombieland,"Ruben Fleischer Jesse Eisenberg, Woody Harrels..."
8805,s8806,Movie,Zoom,"Peter Hewitt Tim Allen, Courteney Cox, Chevy C..."
8806,s8807,Movie,Zubaan,"Mozez Singh Vicky Kaushal, Sarah-Jane Dias, Ra..."

In [107]:
data.dropna(inplace = True)

In [108]:
data

,show_id,type,title,tags
2,s3,TV Show,Ganglands,"Julien Leclercq Sami Bouajila, Tracy Gotoas, S..."
5,s6,TV Show,Midnight Mass,"Mike Flanagan Kate Siegel, Zach Gilford, Hamis..."
6,s7,Movie,My Little Pony: A New Generation,"Robert Cullen, José Luis Ucha Vanessa Hudgens,..."
7,s8,Movie,Sankofa,"Haile Gerima Kofi Ghanaba, Oyafunmike Ogunlano..."
8,s9,TV Show,The Great British Baking Show,"Andy Devonshire Mel Giedroyc, Sue Perkins, Mar..."
...,...,...,...,...
8801,s8802,Movie,Zinzana,"Majid Al Ansari Ali Suliman, Saleh Bakri, Yasa..."
8802,s8803,Movie,Zodiac,"David Fincher Mark Ruffalo, Jake Gyllenhaal, R..."
8804,s8805,Movie,Zombieland,"Ruben Fleischer Jesse Eisenberg, Woody Harrels..."
8805,s8806,Movie,Zoom,"Peter Hewitt Tim Allen, Courteney Cox, Chevy C..."
8806,s8807,Movie,Zubaan,"Mozez Singh Vicky Kaushal, Sarah-Jane Dias, Ra..."

In [109]:
data.reset_index(inplace=True, drop=True)

In [110]:
data

,show_id,type,title,tags
0,s3,TV Show,Ganglands,"Julien Leclercq Sami Bouajila, Tracy Gotoas, S..."
1,s6,TV Show,Midnight Mass,"Mike Flanagan Kate Siegel, Zach Gilford, Hamis..."
2,s7,Movie,My Little Pony: A New Generation,"Robert Cullen, José Luis Ucha Vanessa Hudgens,..."
3,s8,Movie,Sankofa,"Haile Gerima Kofi Ghanaba, Oyafunmike Ogunlano..."
4,s9,TV Show,The Great British Baking Show,"Andy Devonshire Mel Giedroyc, Sue Perkins, Mar..."
...,...,...,...,...
5695,s8802,Movie,Zinzana,"Majid Al Ansari Ali Suliman, Saleh Bakri, Yasa..."
5696,s8803,Movie,Zodiac,"David Fincher Mark Ruffalo, Jake Gyllenhaal, R..."
5697,s8805,Movie,Zombieland,"Ruben Fleischer Jesse Eisenberg, Woody Harrels..."
5698,s8806,Movie,Zoom,"Peter Hewitt Tim Allen, Courteney Cox, Chevy C..."
5699,s8807,Movie,Zubaan,"Mozez Singh Vicky Kaushal, Sarah-Jane Dias, Ra..."

# MODEL CREATION

In [111]:
from sklearn.feature_extraction.text import CountVectorizer

In [112]:
cv = CountVectorizer(max_features=5700, stop_words = 'english')

In [113]:
from sklearn.metrics.pairwise import cosine_similarity

In [114]:
vector = cv.fit_transform(data['tags'].values.astype('U')).toarray()

In [115]:
similarity = cosine_similarity(vector)

In [116]:
similarity

array([[1.        , 0.21764288, 0.05647825, ..., 0.        , 0.03121953,
        0.06024752],
       [0.21764288, 1.        , 0.02594996, ..., 0.02923527, 0.05737753,
        0.02768183],
       [0.05647825, 0.02594996, 1.        , ..., 0.03413944, 0.13400504,
        0.09697623],
       ...,
       [0.        , 0.02923527, 0.03413944, ..., 1.        , 0.1132277 ,
        0.03641785],
       [0.03121953, 0.05737753, 0.13400504, ..., 0.1132277 , 1.        ,
        0.07147417],
       [0.06024752, 0.02768183, 0.09697623, ..., 0.03641785, 0.07147417,
        1.        ]])

# PREDICTING VALUES FROM MODEL

In [117]:
data[data['title'] == 'Zodiac'].index[0]

5696

In [118]:
similar_movies = sorted(list(enumerate(similarity[5696])), reverse=True, key=lambda vector:vector[1])

In [125]:
for i in similar_movies[1:6]:
    print(data.iloc[i[0]].title)
    print(i[1])

To and From New York
0.2637521893583148
Gothika
0.2637521893583148
WHAT DID JACK DO?
0.2449489742783178
Interrogation
0.223606797749979
The Highwaymen
0.2201927530252721

In [120]:
def recommend_movie(movie_name):
    movie_index = data[data['title'] == movie_name].index[0]
    similar_movies = sorted(list(enumerate(similarity[movie_index])), reverse=True, key=lambda vector:vector[1])
    for i in similar_movies[1:6]:
        print(data.iloc[i[0]].title + ' with similarity of ' + str(round(i[1]*100,2)))

In [121]:
recommend_movie('Ganglands')

Bangkok Breaking with similarity of 51.21
Dealer with similarity of 50.83
The Forest of Love: Deep Cut with similarity of 50.74
Sleepless Society: Two Pillows & A Lost Soul with similarity of 49.67
Unlucky Ploy with similarity of 47.36

# DEPLOYING MODEL Web App by STREAMLIT

In [122]:
import pickle as pk

In [123]:
pk.dump(data, open('movie_dataset.pkl','wb'))

In [126]:
pk.dump(similarity, open('similarity.pkl', 'wb'))